---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 0bee91c6b0f868f377d7b8ec991e723a04b46480
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: main
  labels:
    expose: "true"
    app: i-ptg-test-main
    provider: fabric8
    version: 0.1.0
    group: com.redhat
  name: i-ptg-test-main
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: i-ptg-test-main
    provider: fabric8
    group: com.redhat
